/* ========================================
   FUTURISTIC E-COMMERCE PROTOTYPE
   JavaScript - Anime.js Powered
   ======================================== */

// ========================================
// PRODUCT DATA - Everyday Household Items
// ========================================
let products = [
    {
        id: 1,
        name: "Smart Rice Cooker",
        price: 189.00,
        originalPrice: 259.00,
        category: "Kitchen",
        image: "smart.png",
        description: "Multi-function rice cooker with smart timer, fuzzy logic technology, and keep-warm function."
    },
    {
        id: 2,
        name: "Air Purifier HEPA",
        price: 349.00,
        originalPrice: 449.00,
        category: "Home",
        image: "air.png",
        description: "Quiet HEPA air purifier with True HEPA filter, CADR 300m³/h."
    },
    {
        id: 3,
        name: "Robot Vacuum Cleaner",
        price: 599.00,
        originalPrice: 799.00,
        category: "Cleaning",
        image: "vacuum.png",
        description: "Smart robot vacuum with LiDAR navigation, 3000Pa strong suction."
    },
    {
        id: 4,
        name: "Repellent",
        price: 35.00,
        originalPrice: 50.00,
        category: "Kitchen",
        image: "repellent.jpeg",
        description: "Fly repellent that uses wave particles to repel files away that are made from natural plant extract."
    },
    {
        id: 5,
        name: "Buffet Tray",
        price: 150.00,
        originalPrice: 200.00,
        category: "Kitchen",
        image: "buffet tray.jpeg",
        description: "A buffet tray with a combination of natural fly repellent."
    },
    {
        id: 6,
        name: "3 Plant Extract",
        price: 33.00,
        originalPrice: 45.00,
        category: "Kitchen",
        image: "plant extract.jpeg",
        description: "Fly repellent with natural based plant extract generated by wave. Consist of 3 different smell which is rosemary oil, lemon grass oil and pandan leaves oil."
    },
    {
        id: 7,
        name: "Buffet Tray with Repellent",
        price: 175.00,
        originalPrice: 220.00,
        category: "Kitchen",
        image: "buffet tray.jpeg",
        description: "Buffet tray combination with fly repellent and temperature control unit."
    }
];

// Cart data
let cart = [];

// User authentication
let currentUser = null;
let users = [];

// Promo code
let appliedPromo = null;
const promoCodes = {
    'FLYAWAY': 0.15, // 15% discount
};

// ========================================
// DOM ELEMENTS
// ========================================
const productGrid = document.getElementById('productGrid');
const cartItemsContainer = document.getElementById('cartItemsContainer');
const cartCount = document.getElementById('cartCount');
const cartTotalPrice = document.getElementById('cartTotalPrice');
const checkoutBtn = document.getElementById('checkoutBtn');
const searchInput = document.getElementById('searchInput');
const searchBtn = document.getElementById('searchBtn');
const storeView = document.getElementById('storeView');
const checkoutView = document.getElementById('checkoutView');
const backToShopBtn = document.getElementById('backToShopBtn');
const placeOrderBtn = document.getElementById('placeOrderBtn');
const summaryList = document.getElementById('summaryList');
const summaryTotal = document.getElementById('summaryTotal');

// Product Detail Modal elements
const productDetailModal = document.getElementById('productDetailModal');
const detailProductName = document.getElementById('detailProductName');
const detailCategory = document.getElementById('detailCategory');
const detailPrice = document.getElementById('detailPrice');
const detailDescription = document.getElementById('detailDescription');
const detailImage = document.getElementById('detailImage');
const detailAddToCart = document.getElementById('detailAddToCart');
const detailClose = document.getElementById('detailClose');

// Auth elements
const authButtons = document.getElementById('authButtons');
const userMenu = document.getElementById('userMenu');
const userNameDisplay = document.getElementById('userName');
const signInBtn = document.getElementById('signInBtn');
const signUpBtn = document.getElementById('signUpBtn');
const logOutBtn = document.getElementById('logOutBtn');
const signInModal = document.getElementById('signInModal');
const signUpModal = document.getElementById('signUpModal');
const signInForm = document.getElementById('signInForm');
const signUpForm = document.getElementById('signUpForm');
const signInClose = document.getElementById('signInClose');
const signUpClose = document.getElementById('signUpClose');
const signInCancel = document.getElementById('signInCancel');
const signUpCancel = document.getElementById('signUpCancel');

// Modal elements
const sellBtn = document.getElementById('sellBtn');
const modalOverlay = document.getElementById('modalOverlay');
const modalClose = document.getElementById('modalClose');
const cancelBtn = document.getElementById('cancelBtn');
const addProductForm = document.getElementById('addProductForm');

// Image input elements
const imageUrlInput = document.getElementById('productImage');
const imageFileInput = document.getElementById('productImageFile');

// Success message elements
const successMessage = document.getElementById('successMessage');
const successCloseBtn = document.getElementById('successCloseBtn');

// Promo code elements
const promoCodeInput = document.getElementById('promoCodeInput');
const applyPromoBtn = document.getElementById('applyPromoBtn');
const promoMessage = document.getElementById('promoMessage');
const discountRow = document.getElementById('discountRow');
const discountAmount = document.getElementById('discountAmount');

// ========================================
// INITIALIZATION
// ========================================
document.addEventListener('DOMContentLoaded', () => {
    const savedUsers = localStorage.getItem('users');
    if (savedUsers) {
        users = JSON.parse(savedUsers);
    }
    
    const savedUser = localStorage.getItem('currentUser');
    if (savedUser) {
        currentUser = JSON.parse(savedUser);
        updateAuthUI();
    }
    
    renderProducts(products);
    setupEventListeners();
    initAnimations();
});

// ========================================
// ANIME.JS ANIMATIONS
// ========================================
function initAnimations() {
    anime({
        targets: '.header',
        translateY: [-50, 0],
        opacity: [0, 1],
        duration: 800,
        easing: 'easeOutExpo'
    });

    anime({
        targets: '.product-section',
        translateY: [30, 0],
        opacity: [0, 1],
        duration: 800,
        delay: 200,
        easing: 'easeOutExpo'
    });

    anime({
        targets: '.cart-sidebar',
        translateX: [50, 0],
        opacity: [0, 1],
        duration: 800,
        delay: 400,
        easing: 'easeOutExpo'
    });

    anime({
        targets: '.product-card',
        translateY: [20, 0],
        opacity: [0, 1],
        duration: 600,
        delay: anime.stagger(100, {start: 300}),
        easing: 'easeOutQuad'
    });

    anime({
        targets: '.logo h1',
        textShadow: [
            '0 0 10px rgba(0, 245, 212, 0.5)',
            '0 0 20px rgba(0, 245, 212, 0.8)',
            '0 0 10px rgba(0, 245, 212, 0.5)'
        ],
        duration: 2000,
        loop: true,
        easing: 'easeInOutSine'
    });
}

// ========================================
// RENDER PRODUCTS
// ========================================
function renderProducts(productsToRender) {
    if (productsToRender.length === 0) {
        productGrid.innerHTML = `
            <div class="empty-state">
                <i class="fas fa-search"></i>
                <h3>No products found</h3>
                <p>Try a different search term</p>
            </div>
        `;
        return;
    }

    productGrid.innerHTML = productsToRender.map((product, index) => `
        <div class="product-card" data-id="${product.id}" style="opacity: 0;">
            <div class="product-image" onclick="openProductDetail(${product.id})">
                <img src="${product.image}" alt="${product.name}" onerror="this.style.display='none'; this.nextElementSibling.style.display='flex';">
                <i class="fas ${product.icon}" style="display: none;"></i>
                <span class="category-tag">${product.category}</span>
            </div>
            <div class="product-info" onclick="openProductDetail(${product.id})">
                <h3>${product.name}</h3>
                <div class="price">
                    RM ${product.price.toFixed(2)}
                    ${product.originalPrice ? `<span class="original-price">RM ${product.originalPrice.toFixed(2)}</span>` : ''}
                </div>
            </div>
            <button class="add-to-cart-btn" data-id="${product.id}">
                <i class="fas fa-cart-plus"></i> Add to Cart
            </button>
        </div>
    `).join('');

    anime({
        targets: '.product-card',
        translateY: [20, 0],
        opacity: [0, 1],
        duration: 600,
        delay: anime.stagger(100),
        easing: 'easeOutQuad'
    });

    document.querySelectorAll('.add-to-cart-btn').forEach(btn => {
        btn.addEventListener('click', (e) => {
            e.stopPropagation();
            const productId = parseInt(btn.dataset.id);
            addToCart(productId);
        });
    });
}

// ========================================
// PRODUCT DETAIL MODAL
// ========================================
function openProductDetail(productId) {
    const product = products.find(p => p.id === productId);
    if (!product) return;

    detailProductName.textContent = product.name;
    detailCategory.textContent = product.category;
    detailPrice.innerHTML = `RM ${product.price.toFixed(2)}`;
    if (product.originalPrice) {
        detailPrice.innerHTML += ` <span class="original-price">RM ${product.originalPrice.toFixed(2)}</span>`;
    }
    detailDescription.textContent = product.description;
    detailImage.innerHTML = `<img src="${product.image}" alt="${product.name}" onerror="this.style.display='none'; this.nextElementSibling.style.display='flex';"><i class="fas ${product.icon}"></i>`;
    detailAddToCart.dataset.id = product.id;

    productDetailModal.classList.add('active');

    anime({
        targets: '#productDetailModal .modal',
        translateY: [-30, 0],
        opacity: [0, 1],
        duration: 400,
        easing: 'easeOutExpo'
    });
}

function closeProductDetailModal() {
    productDetailModal.classList.remove('active');
}

// ========================================
// CART FUNCTIONS
// ========================================
function addToCart(productId) {
    if (!currentUser) {
        openSignInModal();
        return;
    }
    
    const product = products.find(p => p.id === productId);
    if (!product) return;

    const existingItem = cart.find(item => item.id === productId);
    
    if (existingItem) {
        existingItem.quantity++;
    } else {
        cart.push({
            ...product,
            quantity: 1
        });
    }

    updateCartUI();
    animateAddToCart();
}

function removeFromCart(productId) {
    cart = cart.filter(item => item.id !== productId);
    updateCartUI();
}

function updateCartUI() {
    const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0);
    cartCount.textContent = totalItems;

    const total = cart.reduce((sum, item) => sum + (item.price * item.quantity), 0);
    cartTotalPrice.textContent = `RM ${total.toFixed(2)}`;

    checkoutBtn.disabled = cart.length === 0;

    if (cart.length === 0) {
        cartItemsContainer.innerHTML = `
            <div class="cart-empty">
                <i class="fas fa-shopping-basket"></i>
                <p>Your cart is empty</p>
            </div>
        `;
    } else {
        cartItemsContainer.innerHTML = cart.map(item => `
            <div class="cart-item">
                <div class="cart-item-image">
                    <img src="${item.image}" alt="${item.name}" onerror="this.style.display='none'; this.nextElementSibling.style.display='flex';">
                    <i class="fas ${item.icon}"></i>
                </div>
                <div class="cart-item-details">
                    <h4>${item.name}</h4>
                    <div class="price">RM ${item.price.toFixed(2)} × ${item.quantity}</div>
                </div>
                <button class="cart-item-remove" data-id="${item.id}">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        `).join('');

        document.querySelectorAll('.cart-item-remove').forEach(btn => {
            btn.addEventListener('click', () => {
                const productId = parseInt(btn.dataset.id);
                removeFromCart(productId);
            });
        });
    }
}

function animateAddToCart() {
    anime({
        targets: '.cart-badge',
        scale: [1, 1.3, 1],
        duration: 300,
        easing: 'easeInOutQuad'
    });

    anime({
        targets: '.cart-badge',
        rotate: [0, -10, 10, 0],
        duration: 400,
        easing: 'easeInOutQuad'
    });
}

// ========================================
// SEARCH FUNCTIONALITY
// ========================================
function searchProducts(query) {
    const searchTerm = query.toLowerCase().trim();
    
    if (!searchTerm) {
        renderProducts(products);
        return;
    }

    const filteredProducts = products.filter(product => 
        product.name.toLowerCase().includes(searchTerm) ||
        product.category.toLowerCase().includes(searchTerm) ||
        product.description.toLowerCase().includes(searchTerm)
    );

    renderProducts(filteredProducts);

    anime({
        targets: '.product-card',
        scale: [0.8, 1],
        opacity: [0, 1],
        duration: 400,
        delay: anime.stagger(50),
        easing: 'easeOutBack'
    });
}

// ========================================
// CHECKOUT FUNCTIONALITY
// ========================================
function goToCheckout() {
    if (cart.length === 0) return;

    appliedPromo = null;
    promoCodeInput.value = '';
    promoMessage.textContent = '';
    discountRow.style.display = 'none';

    summaryList.innerHTML = cart.map(item => `
        <div class="summary-item">
            <span class="item-name">${item.name}</span>
            <span class="item-qty">× ${item.quantity}</span>
            <span class="item-price">RM ${(item.price * item.quantity).toFixed(2)}</span>
        </div>
    `).join('');

    const total = cart.reduce((sum, item) => sum + (item.price * item.quantity), 0);
    summaryTotal.textContent = `Total: RM ${total.toFixed(2)}`;

    storeView.classList.add('hidden');
    checkoutView.classList.add('active');

    anime({
        targets: '.checkout-container',
        translateY: [30, 0],
        opacity: [0, 1],
        duration: 600,
        easing: 'easeOutExpo'
    });
}

function backToShop() {
    checkoutView.classList.remove('active');
    storeView.classList.remove('hidden');

    anime({
        targets: '.product-section, .cart-sidebar',
        translateX: [(-30, 0), (30, 0)],
        opacity: [0, 1],
        duration: 600,
        easing: 'easeOutExpo'
    });
}

function placeOrder() {
    successMessage.classList.add('active');

    anime({
        targets: '.success-message',
        scale: [0.5, 1],
        opacity: [0, 1],
        duration: 500,
        easing: 'easeOutBack'
    });

    cart = [];
    appliedPromo = null;
    updateCartUI();
}

function closeSuccessMessage() {
    successMessage.classList.remove('active');
    backToShop();
}

// ========================================
// PROMO CODE FUNCTIONALITY
// ========================================
function applyPromoCode() {
    const code = promoCodeInput.value.trim().toUpperCase();
    
    if (!code) {
        promoMessage.textContent = 'Please enter a promo code';
        promoMessage.className = 'promo-message error';
        return;
    }
    
    if (promoCodes.hasOwnProperty(code)) {
        appliedPromo = code;
        const discountPercent = promoCodes[code] * 100;
        
        const subtotal = cart.reduce((sum, item) => sum + (item.price * item.quantity), 0);
        const discount = subtotal * promoCodes[code];
        const newTotal = subtotal - discount;
        
        discountAmount.textContent = `- RM ${discount.toFixed(2)}`;
        discountRow.style.display = 'flex';
        
        summaryTotal.textContent = `Total: RM ${newTotal.toFixed(2)}`;
        
        promoMessage.textContent = `Promo code applied! You get ${discountPercent}% off!`;
        promoMessage.className = 'promo-message success';
        
        anime({
            targets: '.promo-section',
            scale: [1, 1.02, 1],
            duration: 300,
            easing: 'easeInOutQuad'
        });
    } else {
        promoMessage.textContent = 'Invalid promo code. Try WELCOME for 10% off!';
        promoMessage.className = 'promo-message error';
        appliedPromo = null;
        discountRow.style.display = 'none';
        
        const subtotal = cart.reduce((sum, item) => sum + (item.price * item.quantity), 0);
        summaryTotal.textContent = `Total: RM ${subtotal.toFixed(2)}`;
    }
}

// ========================================
// AUTHENTICATION
// ========================================
function openSignInModal() {
    signInModal.classList.add('active');
    anime({
        targets: '#signInModal .modal',
        translateY: [-30, 0],
        opacity: [0, 1],
        duration: 400,
        easing: 'easeOutExpo'
    });
}

function closeSignInModal() {
    signInModal.classList.remove('active');
    signInForm.reset();
}

function openSignUpModal() {
    signUpModal.classList.add('active');
    anime({
        targets: '#signUpModal .modal',
        translateY: [-30, 0],
        opacity: [0, 1],
        duration: 400,
        easing: 'easeOutExpo'
    });
}

function closeSignUpModal() {
    signUpModal.classList.remove('active');
    signUpForm.reset();
}

function handleSignIn(e) {
    e.preventDefault();
    
    const email = document.getElementById('signInEmail').value;
    const password = document.getElementById('signInPassword').value;
    
    const user = users.find(u => u.email === email && u.password === password);
    
    if (user) {
        currentUser = user;
        localStorage.setItem('currentUser', JSON.stringify(currentUser));
        updateAuthUI();
        closeSignInModal();
        alert(`Welcome back, ${user.name}!`);
    } else {
        alert('Invalid email or password. Please try again.');
    }
}

function handleSignUp(e) {
    e.preventDefault();
    
    const name = document.getElementById('signUpName').value;
    const email = document.getElementById('signUpEmail').value;
    const password = document.getElementById('signUpPassword').value;
    const phone = document.getElementById('signUpPhone').value;
    
    const existingUser = users.find(u => u.email === email);
    
    if (existingUser) {
        alert('Email already registered. Please sign in instead.');
        return;
    }
    
    const newUser = {
        id: Date.now(),
        name,
        email,
        password,
        phone
    };
    
    users.push(newUser);
    localStorage.setItem('users', JSON.stringify(users));
    
    currentUser = newUser;
    localStorage.setItem('currentUser', JSON.stringify(currentUser));
    
    updateAuthUI();
    closeSignUpModal();
    
    alert(`Welcome, ${name}! Your account has been created successfully.`);
}

function handleLogOut() {
    currentUser = null;
    localStorage.removeItem('currentUser');
    cart = [];
    appliedPromo = null;
    updateCartUI();
    updateAuthUI();
}

function updateAuthUI() {
    if (currentUser) {
        authButtons.style.display = 'none';
        userMenu.style.display = 'flex';
        userNameDisplay.textContent = currentUser.name;
    } else {
        authButtons.style.display = 'flex';
        userMenu.style.display = 'none';
    }
}

// ========================================
// ADD PRODUCT FUNCTIONALITY
// ========================================
function openAddProductModal() {
    if (!currentUser) {
        openSignInModal();
        return;
    }
    
    modalOverlay.classList.add('active');
    
    anime({
        targets: '.modal',
        translateY: [-30, 0],
        opacity: [0, 1],
        duration: 400,
        easing: 'easeOutExpo'
    });
}

function closeAddProductModal() {
    modalOverlay.classList.remove('active');
    addProductForm.reset();
    
    // Reset image inputs
    imageUrlInput.style.display = 'block';
    imageFileInput.style.display = 'none';
    document.querySelector('input[name="imageSource"][value="url"]').checked = true;
}

function handleAddProduct(e) {
    e.preventDefault();

    const name = document.getElementById('productName').value;
    const price = parseFloat(document.getElementById('productPrice').value);
    const category = document.getElementById('productCategory').value;
    const description = document.getElementById('productDescription').value;
    const originalPrice = parseFloat(document.getElementById('productOriginalPrice').value) || null;
    
    // Get image source (URL or file)
    const imageSource = document.querySelector('input[name="imageSource"]:checked').value;
    let imageUrl = '';
    
    if (imageSource === 'url') {
        imageUrl = document.getElementById('productImage').value;
    } else {
        // Handle file upload - convert to data URL
        const file = document.getElementById('productImageFile').files[0];
        if (file) {
            imageUrl = URL.createObjectURL(file);
        }
    }

    const categoryIcons = {
        'Kitchen': 'fa-blender',
        'Home': 'fa-house',
        'Cleaning': 'fa-broom',
        'Lighting': 'fa-lightbulb',
        'Cooling': 'fa-fan',
        'Electronics': 'fa-plug',
        'Furniture': 'fa-couch',
        'Other': 'fa-box'
    };

    const newProduct = {
        id: products.length + 1,
        name,
        price,
        originalPrice,
        category,
        icon: categoryIcons[category] || 'fa-box',
        image: imageUrl || 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop',
        description
    };

    products.unshift(newProduct);
    renderProducts(products);
    closeAddProductModal();

    anime({
        targets: '.product-card:first-child',
        scale: [0.5, 1],
        rotate: [(-10, 10), 0],
        duration: 600,
        easing: 'easeOutBack'
    });
}

// ========================================
// EVENT LISTENERS
// ========================================
function setupEventListeners() {
    // Search
    searchBtn.addEventListener('click', () => {
        searchProducts(searchInput.value);
    });

    searchInput.addEventListener('keyup', (e) => {
        if (e.key === 'Enter') {
            searchProducts(searchInput.value);
        } else {
            searchProducts(searchInput.value);
        }
    });

    // Checkout
    checkoutBtn.addEventListener('click', goToCheckout);
    backToShopBtn.addEventListener('click', backToShop);
    placeOrderBtn.addEventListener('click', placeOrder);
    successCloseBtn.addEventListener('click', closeSuccessMessage);

    // Promo code
    applyPromoBtn.addEventListener('click', applyPromoCode);
    promoCodeInput.addEventListener('keyup', (e) => {
        if (e.key === 'Enter') {
            applyPromoCode();
        }
    });

    // Product Detail Modal
    detailClose.addEventListener('click', closeProductDetailModal);
    productDetailModal.addEventListener('click', (e) => {
        if (e.target === productDetailModal) closeProductDetailModal();
    });
    detailAddToCart.addEventListener('click', () => {
        const productId = parseInt(detailAddToCart.dataset.id);
        addToCart(productId);
    });

    // Authentication
    signInBtn.addEventListener('click', openSignInModal);
    signUpBtn.addEventListener('click', openSignUpModal);
    logOutBtn.addEventListener('click', handleLogOut);
    signInForm.addEventListener('submit', handleSignIn);
    signUpForm.addEventListener('submit', handleSignUp);
    signInClose.addEventListener('click', closeSignInModal);
    signUpClose.addEventListener('click', closeSignUpModal);
    signInCancel.addEventListener('click', closeSignInModal);
    signUpCancel.addEventListener('click', closeSignUpModal);
    
    signInModal.addEventListener('click', (e) => {
        if (e.target === signInModal) closeSignInModal();
    });
    signUpModal.addEventListener('click', (e) => {
        if (e.target === signUpModal) closeSignUpModal();
    });

    // Add Product Modal
    sellBtn.addEventListener('click', openAddProductModal);
    modalClose.addEventListener('click', closeAddProductModal);
    cancelBtn.addEventListener('click', closeAddProductModal);
    modalOverlay.addEventListener('click', (e) => {
        if (e.target === modalOverlay) {
            closeAddProductModal();
        }
    });
    addProductForm.addEventListener('submit', handleAddProduct);
    
    // Image source toggle
    document.querySelectorAll('input[name="imageSource"]').forEach(radio => {
        radio.addEventListener('change', (e) => {
            if (e.target.value === 'url') {
                imageUrlInput.style.display = 'block';
                imageFileInput.style.display = 'none';
            } else {
                imageUrlInput.style.display = 'none';
                imageFileInput.style.display = 'block';
            }
        });
    });

    // Keyboard shortcuts
    document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape') {
            closeAddProductModal();
            closeSignInModal();
            closeSignUpModal();
            closeSuccessMessage();
            closeProductDetailModal();
        }
    });
}

